"""
Fan Hub Plus - master test data.

This single Python module is the source of truth for the demo/test data.
`build_seed.py` turns it into /database/seed.sql and `gen_images.py`
renders the dual poster artwork referenced by every row.
All text is original platform copy; titles, franchises and dates are
factual references used for demonstration (see README "Test data").
"""

CATEGORIES = [
    # slug, name, tagline, description, accent, secondary, icon
    ("anime", "Anime", "Blades, spirits and endless arcs",
     "From shonen battles to quiet slice-of-life journeys, the Anime realm collects series, films and studios that define Japanese animation.",
     "#E11D48", "#F9A8D4", "katana"),
    ("gaming", "Gaming", "Press start on legendary worlds",
     "Open worlds, soulslike challenges and indie gems. The Gaming realm tracks the titles, heroes and soundtracks players love.",
     "#22C55E", "#D4AF37", "controller"),
    ("movies", "Movies", "Cinema that changed the multiverse",
     "Blockbusters, animated landmarks and director-driven epics, curated with trailers, cast profiles and release news.",
     "#F59E0B", "#DC2626", "film-reel"),
    ("tv-shows", "TV Shows", "Binge-worthy sagas, season by season",
     "Prestige dramas, animated series and streaming phenomena with season guides, characters and premiere events.",
     "#3B82F6", "#22D3EE", "tv"),
    ("k-pop", "K-Pop", "Light sticks up, the stage is yours",
     "Albums, music videos, comeback schedules and group profiles from the artists leading the Korean wave.",
     "#EC4899", "#22D3EE", "microphone"),
    ("comics", "Comics", "Panels that built modern myth",
     "Graphic novels and landmark runs from the publishers and creators who shaped superheroes and beyond.",
     "#FACC15", "#EF4444", "mask"),
    ("manga", "Manga", "Ink, paper and legendary arcs",
     "Seinen, shonen and cult classics with volume guides, creator notes and character deep dives.",
     "#E5E7EB", "#DC2626", "manga"),
    ("cosplay", "Cosplay", "Craft the character, own the stage",
     "Build guides, crafting techniques, photography tips and masquerade highlights from the cosplay community.",
     "#A855F7", "#D4AF37", "cosplay-mask"),
]

GENRES = [
    "Action", "Adventure", "Fantasy", "Sci-Fi", "Drama", "Comedy", "Romance", "Horror",
    "Thriller", "Mystery", "Slice of Life", "Supernatural", "Superhero", "RPG", "Open World",
    "Platformer", "Strategy", "Pop", "Hip-Hop", "R&B", "Dance", "Crime", "Historical",
    "Sports", "Psychological", "Crafting", "Tutorial", "Showcase", "Animation", "Dark Fantasy",
]

TAGS = [
    # name, color
    ("Limited Edition", "#D4AF37"),
    ("Pre-Order", "#22D3EE"),
    ("Collectible", "#A855F7"),
    ("Exclusive", "#E11D48"),
    ("New Arrival", "#22C55E"),
    ("Trending", "#F59E0B"),
    ("Official", "#3B82F6"),
    ("Fan Favorite", "#EC4899"),
    ("Soundtrack", "#14B8A6"),
    ("Behind the Scenes", "#64748B"),
    ("Tutorial", "#84CC16"),
    ("Open Movie", "#F97316"),
]

# ---------------------------------------------------------------------------
# CONTENT: category -> list of (title, contentType, format, year, creator,
#                                genres, synopsis, seasons, episodes)
# contentType follows the SRS: Article | Video | Audio | Image
# ---------------------------------------------------------------------------
CONTENT = {
    "anime": [
        ("Attack on Titan", "Video", "Series", 2013, "Wit Studio / MAPPA", ["Action", "Dark Fantasy", "Drama"],
         "Humanity survives behind colossal walls until the Titans break through, and Eren Yeager vows to uncover the truth behind the world's cruelest mystery.", 4, 89),
        ("Demon Slayer: Kimetsu no Yaiba", "Video", "Series", 2019, "ufotable", ["Action", "Supernatural", "Adventure"],
         "After demons slaughter his family, Tanjiro Kamado joins the Demon Slayer Corps to cure his sister Nezuko and hunt the demon who started it all.", 4, 63),
        ("Jujutsu Kaisen", "Video", "Series", 2020, "MAPPA", ["Action", "Supernatural"],
         "Yuji Itadori swallows a cursed finger and becomes the vessel of Ryomen Sukuna, pulling him into a hidden war between sorcerers and curses.", 2, 47),
        ("One Piece", "Video", "Series", 1999, "Toei Animation", ["Adventure", "Comedy", "Action"],
         "Monkey D. Luffy and the Straw Hat crew sail the Grand Line in search of the legendary treasure that will make him King of the Pirates.", 21, 1100),
        ("Naruto Shippuden", "Video", "Series", 2007, "Studio Pierrot", ["Action", "Adventure"],
         "Naruto Uzumaki returns to the Hidden Leaf after years of training, ready to rescue Sasuke and face the Akatsuki.", 21, 500),
        ("Fullmetal Alchemist: Brotherhood", "Video", "Series", 2009, "Bones", ["Adventure", "Fantasy", "Drama"],
         "Brothers Edward and Alphonse Elric search for the Philosopher's Stone after a forbidden transmutation costs them dearly.", 1, 64),
        ("Spy x Family", "Video", "Series", 2022, "Wit Studio / CloverWorks", ["Comedy", "Action", "Slice of Life"],
         "A spy, an assassin and a telepathic child form a fake family, each hiding a secret from the others.", 3, 37),
        ("Frieren: Beyond Journey's End", "Video", "Series", 2023, "Madhouse", ["Fantasy", "Adventure", "Drama"],
         "An elf mage who outlived her heroic party retraces their old journey and learns what the years with them truly meant.", 2, 38),
        ("Chainsaw Man", "Video", "Series", 2022, "MAPPA", ["Action", "Horror", "Supernatural"],
         "Debt-ridden Denji merges with his chainsaw devil dog Pochita and is recruited as a Public Safety Devil Hunter.", 1, 12),
        ("My Hero Academia", "Video", "Series", 2016, "Bones", ["Superhero", "Action", "Comedy"],
         "Born without a Quirk, Izuku Midoriya inherits the power of the world's greatest hero and enrolls at U.A. High.", 8, 170),
        ("Cowboy Bebop", "Video", "Series", 1998, "Sunrise", ["Sci-Fi", "Action", "Drama"],
         "Bounty hunters aboard the spaceship Bebop chase criminals across the solar system to a jazz soundtrack.", 1, 26),
        ("Your Name", "Video", "Film", 2016, "CoMix Wave Films", ["Romance", "Fantasy", "Drama"],
         "Two teenagers who have never met begin swapping bodies, and a comet ties their fates together.", None, None),
    ],
    "gaming": [
        ("The Legend of Zelda: Tears of the Kingdom", "Video", "Game", 2023, "Nintendo", ["Adventure", "Open World", "Action"],
         "Link explores the skies, surface and depths of Hyrule, building contraptions to stop a returning ancient evil.", None, None),
        ("Elden Ring", "Video", "Game", 2022, "FromSoftware", ["RPG", "Dark Fantasy", "Open World"],
         "Rise, Tarnished, and cross the Lands Between to restore the shattered Elden Ring and become Elden Lord.", None, None),
        ("God of War Ragnarok", "Video", "Game", 2022, "Santa Monica Studio", ["Action", "Adventure"],
         "Kratos and Atreus journey across the Nine Realms as Fimbulwinter heralds the end of days.", None, None),
        ("Cyberpunk 2077", "Video", "Game", 2020, "CD Projekt Red", ["RPG", "Sci-Fi", "Open World"],
         "Mercenary V hunts a one-of-a-kind implant in Night City, a megacity obsessed with power and body modification.", None, None),
        ("The Witcher 3: Wild Hunt", "Video", "Game", 2015, "CD Projekt Red", ["RPG", "Fantasy", "Open World"],
         "Geralt of Rivia searches a war-torn continent for Ciri, the child of prophecy pursued by the Wild Hunt.", None, None),
        ("Final Fantasy VII Rebirth", "Video", "Game", 2024, "Square Enix", ["RPG", "Adventure"],
         "Cloud and his companions leave Midgar behind and chase Sephiroth across a vast, reimagined world.", None, None),
        ("Baldur's Gate 3", "Video", "Game", 2023, "Larian Studios", ["RPG", "Strategy", "Fantasy"],
         "Infected by a mind flayer parasite, your party must resist a growing power in a deeply reactive D&D adventure.", None, None),
        ("Minecraft", "Image", "Game", 2011, "Mojang Studios", ["Adventure", "Crafting"],
         "Mine, build and survive in an endless block world that became the best-selling video game of all time.", None, None),
        ("Hades", "Video", "Game", 2020, "Supergiant Games", ["Action", "RPG"],
         "Zagreus, son of Hades, battles his way out of the Underworld with help from the gods of Olympus.", None, None),
        ("Genshin Impact", "Video", "Game", 2020, "HoYoverse", ["RPG", "Open World", "Fantasy"],
         "A traveler searches for their lost sibling across the elemental nations of Teyvat.", None, None),
        ("Red Dead Redemption 2", "Video", "Game", 2018, "Rockstar Games", ["Action", "Adventure", "Open World"],
         "Arthur Morgan and the Van der Linde gang fight to survive as the age of outlaws comes to an end.", None, None),
        ("Hollow Knight", "Audio", "Game", 2017, "Team Cherry", ["Platformer", "Adventure", "Dark Fantasy"],
         "Descend into the ruined bug kingdom of Hallownest, a hand-drawn metroidvania with a haunting score.", None, None),
    ],
    "movies": [
        ("Dune: Part Two", "Video", "Film", 2024, "Denis Villeneuve", ["Sci-Fi", "Adventure", "Drama"],
         "Paul Atreides unites with Chani and the Fremen while seeking revenge against those who destroyed his family.", None, None),
        ("Spider-Man: Across the Spider-Verse", "Video", "Film", 2023, "Sony Pictures Animation", ["Superhero", "Animation", "Action"],
         "Miles Morales is catapulted across the Multiverse and clashes with the Spider-Society over the meaning of heroism.", None, None),
        ("Avengers: Endgame", "Video", "Film", 2019, "Marvel Studios", ["Superhero", "Action", "Sci-Fi"],
         "The remaining Avengers assemble once more to reverse Thanos's snap and restore the universe.", None, None),
        ("The Dark Knight", "Video", "Film", 2008, "Christopher Nolan", ["Superhero", "Crime", "Thriller"],
         "Batman faces the Joker, a criminal mastermind who pushes Gotham City and its heroes to the edge.", None, None),
        ("Interstellar", "Video", "Film", 2014, "Christopher Nolan", ["Sci-Fi", "Drama", "Adventure"],
         "A team of explorers travels through a wormhole in search of a new home for humanity.", None, None),
        ("Everything Everywhere All at Once", "Video", "Film", 2022, "Daniels", ["Sci-Fi", "Comedy", "Action"],
         "A laundromat owner discovers she must connect with parallel-universe versions of herself to save existence.", None, None),
        ("Spirited Away", "Video", "Film", 2001, "Studio Ghibli", ["Fantasy", "Animation", "Adventure"],
         "Ten-year-old Chihiro wanders into a world of spirits and must work in a bathhouse to free her parents.", None, None),
        ("Top Gun: Maverick", "Video", "Film", 2022, "Joseph Kosinski", ["Action", "Drama"],
         "Pete 'Maverick' Mitchell trains a new generation of elite pilots for a near-impossible mission.", None, None),
        ("Oppenheimer", "Video", "Film", 2023, "Christopher Nolan", ["Historical", "Drama", "Thriller"],
         "The story of J. Robert Oppenheimer and the creation of the atomic bomb during the Manhattan Project.", None, None),
        ("Mad Max: Fury Road", "Video", "Film", 2015, "George Miller", ["Action", "Sci-Fi", "Adventure"],
         "In a post-apocalyptic wasteland, Max and Furiosa flee a tyrant across the desert in a war rig.", None, None),
        ("Inception", "Video", "Film", 2010, "Christopher Nolan", ["Sci-Fi", "Thriller", "Action"],
         "A thief who steals secrets through dream-sharing is offered a chance to plant an idea instead.", None, None),
        ("The Lord of the Rings: The Return of the King", "Video", "Film", 2003, "Peter Jackson", ["Fantasy", "Adventure", "Action"],
         "Frodo and Sam near Mount Doom as the free peoples of Middle-earth make their final stand.", None, None),
    ],
    "tv-shows": [
        ("Stranger Things", "Video", "Series", 2016, "The Duffer Brothers", ["Sci-Fi", "Horror", "Mystery"],
         "When a boy vanishes in Hawkins, Indiana, his friends uncover secret experiments and a terrifying parallel dimension.", 5, 42),
        ("The Last of Us", "Video", "Series", 2023, "Craig Mazin & Neil Druckmann", ["Drama", "Horror", "Adventure"],
         "Smuggler Joel escorts Ellie across a post-pandemic America in a story of survival and love.", 2, 16),
        ("House of the Dragon", "Video", "Series", 2022, "Ryan Condal", ["Fantasy", "Drama"],
         "Two centuries before Game of Thrones, House Targaryen tears itself apart in the civil war called the Dance of the Dragons.", 2, 18),
        ("Arcane", "Video", "Series", 2021, "Fortiche / Riot Games", ["Animation", "Action", "Drama"],
         "Sisters Vi and Jinx end up on opposite sides of a conflict between the cities of Piltover and Zaun.", 2, 18),
        ("The Mandalorian", "Video", "Series", 2019, "Jon Favreau", ["Sci-Fi", "Adventure", "Action"],
         "A lone bounty hunter protects a mysterious child in the outer reaches of the galaxy.", 3, 24),
        ("Breaking Bad", "Video", "Series", 2008, "Vince Gilligan", ["Crime", "Drama", "Thriller"],
         "A chemistry teacher turned drug manufacturer transforms into the feared Heisenberg.", 5, 62),
        ("Wednesday", "Video", "Series", 2022, "Alfred Gough & Miles Millar", ["Mystery", "Comedy", "Supernatural"],
         "Wednesday Addams investigates a string of monstrous killings at Nevermore Academy.", 2, 16),
        ("The Boys", "Video", "Series", 2019, "Eric Kripke", ["Superhero", "Action", "Comedy"],
         "A group of vigilantes takes on corrupt superheroes who abuse their fame and power.", 4, 32),
        ("Squid Game", "Video", "Series", 2021, "Hwang Dong-hyuk", ["Thriller", "Drama"],
         "Hundreds of desperate players compete in deadly children's games for a massive cash prize.", 3, 22),
        ("Loki", "Video", "Series", 2021, "Marvel Studios", ["Superhero", "Sci-Fi", "Comedy"],
         "The God of Mischief is recruited by the Time Variance Authority to repair the broken timeline.", 2, 12),
        ("Game of Thrones", "Video", "Series", 2011, "David Benioff & D. B. Weiss", ["Fantasy", "Drama", "Action"],
         "Noble houses wage war for the Iron Throne while an ancient threat awakens beyond the Wall.", 8, 73),
        ("Shogun", "Video", "Series", 2024, "Rachel Kondo & Justin Marks", ["Historical", "Drama"],
         "An English navigator shipwrecked in feudal Japan becomes entangled in the power struggle of Lord Toranaga.", 1, 10),
    ],
    "k-pop": [
        ("BTS - Map of the Soul: 7", "Audio", "Album", 2020, "BTS / BIGHIT MUSIC", ["Pop", "Hip-Hop"],
         "BTS reflect on seven years together in a studio album featuring the global single 'ON'.", None, 20),
        ("BLACKPINK - Born Pink", "Audio", "Album", 2022, "BLACKPINK / YG Entertainment", ["Pop", "Hip-Hop"],
         "The quartet's second studio album, led by 'Pink Venom' and 'Shut Down'.", None, 8),
        ("Stray Kids - 5-STAR", "Audio", "Album", 2023, "Stray Kids / JYP Entertainment", ["Hip-Hop", "Pop"],
         "Stray Kids' third studio album and its title track 'S-Class' showcase the group's self-produced sound.", None, 12),
        ("NewJeans - Get Up", "Audio", "EP", 2023, "NewJeans / ADOR", ["Pop", "R&B"],
         "A breezy EP that includes 'Super Shy' and 'ETA', capturing the group's Y2K-inspired style.", None, 6),
        ("SEVENTEEN - FML", "Audio", "EP", 2023, "SEVENTEEN / PLEDIS", ["Pop", "Dance"],
         "The group's tenth mini album, featuring the double title tracks 'F*ck My Life' and 'Super'.", None, 6),
        ("TWICE - Formula of Love: O+T=<3", "Audio", "Album", 2021, "TWICE / JYP Entertainment", ["Pop", "Dance"],
         "TWICE's third studio album, led by the bright single 'Scientist'.", None, 17),
        ("aespa - Armageddon", "Audio", "Album", 2024, "aespa / SM Entertainment", ["Pop", "Dance"],
         "aespa's first full-length album expands their virtual-world concept with 'Supernova' and 'Armageddon'.", None, 10),
        ("LE SSERAFIM - Easy", "Video", "EP", 2024, "LE SSERAFIM / SOURCE MUSIC", ["Pop", "Hip-Hop"],
         "A mini album that pairs a trap-influenced title track with striking performance videos.", None, 5),
        ("IVE - I've IVE", "Video", "Album", 2023, "IVE / Starship", ["Pop", "Dance"],
         "IVE's first studio album with the title track 'I AM', a confident anthem about self-belief.", None, 11),
        ("ATEEZ - The World EP.FIN: Will", "Audio", "Album", 2023, "ATEEZ / KQ Entertainment", ["Hip-Hop", "Dance"],
         "The finale of ATEEZ's 'The World' series, led by the high-energy 'Crazy Form'.", None, 11),
        ("EXO - EXIST", "Audio", "Album", 2023, "EXO / SM Entertainment", ["Pop", "R&B"],
         "EXO's seventh studio album marks their return with the smooth title track 'Cream Soda'.", None, 9),
        ("ENHYPEN - Dark Blood", "Video", "EP", 2023, "ENHYPEN / BELIFT LAB", ["Pop", "Dance"],
         "A dark, cinematic mini album built around the title track 'Bite Me'.", None, 6),
    ],
    "comics": [
        ("Watchmen", "Image", "Graphic Novel", 1986, "Alan Moore & Dave Gibbons", ["Superhero", "Mystery", "Drama"],
         "When a costumed hero is murdered, retired vigilantes uncover a conspiracy in an alternate 1985.", None, 12),
        ("The Sandman", "Image", "Comic Series", 1989, "Neil Gaiman", ["Fantasy", "Horror", "Drama"],
         "Dream of the Endless escapes a century of captivity and rebuilds his realm.", None, 75),
        ("Batman: The Killing Joke", "Image", "Graphic Novel", 1988, "Alan Moore & Brian Bolland", ["Superhero", "Crime", "Psychological"],
         "The Joker sets out to prove that one bad day can drive anyone to madness.", None, 1),
        ("Saga", "Image", "Comic Series", 2012, "Brian K. Vaughan & Fiona Staples", ["Sci-Fi", "Fantasy", "Romance"],
         "Lovers from warring races flee across the galaxy to raise their newborn daughter.", None, 66),
        ("The Walking Dead", "Image", "Comic Series", 2003, "Robert Kirkman", ["Horror", "Drama"],
         "Deputy Rick Grimes wakes into a zombie apocalypse and leads survivors through a collapsing world.", None, 193),
        ("The Amazing Spider-Man", "Image", "Comic Series", 1963, "Stan Lee & Steve Ditko", ["Superhero", "Action"],
         "Peter Parker balances everyday life with his responsibility as Spider-Man.", None, 900),
        ("X-Men: Days of Future Past", "Image", "Comic Arc", 1981, "Chris Claremont & John Byrne", ["Superhero", "Sci-Fi"],
         "A mutant from a dystopian future travels back to prevent the assassination that dooms mutantkind.", None, 2),
        ("Maus", "Image", "Graphic Novel", 1991, "Art Spiegelman", ["Historical", "Drama"],
         "A Pulitzer Prize-winning memoir of the Holocaust told through the story of the author's father.", None, 2),
        ("V for Vendetta", "Image", "Graphic Novel", 1988, "Alan Moore & David Lloyd", ["Thriller", "Drama"],
         "A masked revolutionary known as V wages war on a totalitarian British regime.", None, 10),
        ("Invincible", "Image", "Comic Series", 2003, "Robert Kirkman & Cory Walker", ["Superhero", "Action", "Drama"],
         "Mark Grayson inherits powers from his father, the planet's greatest hero, and learns a dark truth.", None, 144),
        ("Hellboy: Seed of Destruction", "Image", "Graphic Novel", 1994, "Mike Mignola", ["Supernatural", "Action", "Horror"],
         "The paranormal investigator Hellboy confronts the sorcerer who summoned him to Earth.", None, 4),
        ("Batman: Year One", "Image", "Comic Arc", 1987, "Frank Miller & David Mazzucchelli", ["Superhero", "Crime"],
         "Bruce Wayne's first year as Batman and James Gordon's arrival in a corrupt Gotham.", None, 4),
    ],
    "manga": [
        ("Berserk", "Image", "Manga", 1989, "Kentaro Miura", ["Dark Fantasy", "Action", "Drama"],
         "Guts, the Black Swordsman, seeks revenge against the former friend who betrayed him.", None, 42),
        ("Vagabond", "Image", "Manga", 1998, "Takehiko Inoue", ["Historical", "Action", "Drama"],
         "A fictional retelling of the life of legendary swordsman Miyamoto Musashi.", None, 37),
        ("Monster", "Image", "Manga", 1994, "Naoki Urasawa", ["Thriller", "Mystery", "Psychological"],
         "A surgeon who saved a boy's life hunts the serial killer that boy grew up to become.", None, 18),
        ("Death Note", "Image", "Manga", 2003, "Tsugumi Ohba & Takeshi Obata", ["Thriller", "Supernatural", "Psychological"],
         "A student finds a notebook that kills anyone whose name is written in it.", None, 12),
        ("Tokyo Ghoul", "Image", "Manga", 2011, "Sui Ishida", ["Horror", "Action", "Supernatural"],
         "After a fateful encounter, college student Ken Kaneki becomes a half-ghoul.", None, 14),
        ("Vinland Saga", "Image", "Manga", 2005, "Makoto Yukimura", ["Historical", "Action", "Drama"],
         "Young Thorfinn follows his father's killer through Viking-age Europe, seeking a duel.", None, 28),
        ("Blue Lock", "Image", "Manga", 2018, "Muneyuki Kaneshiro & Yusuke Nomura", ["Sports", "Drama"],
         "Three hundred strikers compete in a radical program to forge Japan's ultimate egoist forward.", None, 30),
        ("Kagurabachi", "Image", "Manga", 2023, "Takeru Hokazono", ["Action", "Supernatural"],
         "Chihiro Rokuhira hunts the sorcerers who stole the enchanted blades forged by his father.", None, 8),
        ("Dandadan", "Image", "Manga", 2021, "Yukinobu Tatsu", ["Supernatural", "Comedy", "Action"],
         "A girl who believes in ghosts and a boy who believes in aliens discover both are real.", None, 18),
        ("Akira", "Image", "Manga", 1982, "Katsuhiro Otomo", ["Sci-Fi", "Action"],
         "In Neo-Tokyo, biker gang leader Kaneda tries to save his friend Tetsuo from a government project.", None, 6),
        ("Slam Dunk", "Image", "Manga", 1990, "Takehiko Inoue", ["Sports", "Comedy", "Drama"],
         "Delinquent Hanamichi Sakuragi joins the basketball team to impress a girl and finds his calling.", None, 31),
        ("Hunter x Hunter", "Image", "Manga", 1998, "Yoshihiro Togashi", ["Adventure", "Action", "Fantasy"],
         "Gon Freecss becomes a Hunter to find the father who left him to pursue the same career.", None, 38),
    ],
    "cosplay": [
        ("Worbla Armor Masterclass", "Video", "Guide", 2025, "Fan Hub Plus Studio", ["Crafting", "Tutorial"],
         "Heat-shape thermoplastic sheets into sharp, wearable armor with clean edges and durable finishes.", None, None),
        ("EVA Foam Basics for First-Time Builders", "Article", "Guide", 2025, "Fan Hub Plus Studio", ["Crafting", "Tutorial"],
         "Patterning, cutting, beveling and sealing foam for your first armor build.", None, None),
        ("Wig Styling: Gravity-Defying Spikes", "Video", "Guide", 2024, "Fan Hub Plus Studio", ["Crafting", "Tutorial"],
         "Tease, glue and heat-set anime wigs so every spike survives a full convention day.", None, None),
        ("Masquerade Highlights: Stage Presence", "Video", "Showcase", 2025, "Fan Hub Plus Studio", ["Showcase"],
         "What judges look for on the masquerade stage, from walk-on timing to character performance.", None, None),
        ("Cosplay Photography Lighting Guide", "Article", "Guide", 2024, "Fan Hub Plus Studio", ["Tutorial", "Showcase"],
         "Rim lights, gels and golden hour: lighting setups that make costumes look cinematic.", None, None),
        ("Sewing Fantasy Capes and Cloaks", "Article", "Guide", 2024, "Fan Hub Plus Studio", ["Crafting", "Tutorial"],
         "Choose fabrics, draft circle capes and add weathering for a battle-worn look.", None, None),
        ("LED Props and Glow Effects", "Video", "Guide", 2025, "Fan Hub Plus Studio", ["Crafting", "Tutorial"],
         "Wire safe, battery-powered LEDs into swords, staffs and armor for convention-ready glow.", None, None),
        ("Character Transformation Makeup", "Video", "Guide", 2024, "Fan Hub Plus Studio", ["Tutorial"],
         "Contouring, prosthetic basics and color matching to transform into any character.", None, None),
        ("Building a Convention-Safe Sword Prop", "Article", "Guide", 2025, "Fan Hub Plus Studio", ["Crafting", "Tutorial"],
         "Lightweight cores, blunt edges and peace-bonding tips so your blade passes every prop check.", None, None),
        ("Convention Survival Guide", "Article", "Guide", 2025, "Fan Hub Plus Studio", ["Tutorial"],
         "Repair kits, hydration, scheduling photoshoots and staying comfortable in costume all day.", None, None),
        ("Planning a Group Cosplay", "Article", "Guide", 2024, "Fan Hub Plus Studio", ["Tutorial", "Showcase"],
         "Coordinate a squad build with shared timelines, color palettes and group poses.", None, None),
        ("Gallery: Realm Cosplay Showcase", "Image", "Showcase", 2025, "Fan Hub Plus Community", ["Showcase"],
         "A curated gallery of standout community builds from across all eight realms.", None, None),
    ],
}

# ---------------------------------------------------------------------------
# CHARACTERS: (category, name, fandom, contentTitle|None, role, power, quote, bio,
#              strength, intelligence, agility, charisma)
# ---------------------------------------------------------------------------
CHARACTERS = [
    ("anime", "Eren Yeager", "Attack on Titan", "Attack on Titan", "Protagonist", "Attack Titan",
     "If you win, you live. If you lose, you die.",
     "A fierce young soldier of the Survey Corps who can transform into a Titan and whose quest for freedom reshapes his entire world.", 88, 74, 80, 70),
    ("anime", "Tanjiro Kamado", "Demon Slayer", "Demon Slayer: Kimetsu no Yaiba", "Protagonist", "Water and Sun Breathing",
     "No matter how many people you may lose, you have no choice but to go on living.",
     "A kind-hearted boy with an extraordinary sense of smell who became a Demon Slayer to save his sister Nezuko.", 78, 72, 86, 90),
    ("anime", "Satoru Gojo", "Jujutsu Kaisen", "Jujutsu Kaisen", "Mentor", "Limitless and Six Eyes",
     "Throughout heaven and earth, I alone am the honored one.",
     "The strongest jujutsu sorcerer of his era and a teacher at Tokyo Jujutsu High who protects the next generation.", 96, 92, 95, 94),
    ("anime", "Monkey D. Luffy", "One Piece", "One Piece", "Captain", "Gum-Gum Fruit",
     "I'm going to be King of the Pirates!",
     "The rubber-bodied captain of the Straw Hat Pirates whose optimism turns rivals into lifelong allies.", 94, 55, 90, 98),
    ("gaming", "Link", "The Legend of Zelda", "The Legend of Zelda: Tears of the Kingdom", "Hero", "Master Sword and Ultrahand",
     "...",
     "The silent champion of Hyrule who wakes again and again to defeat Ganon and protect Princess Zelda.", 80, 78, 88, 76),
    ("gaming", "Kratos", "God of War", "God of War Ragnarok", "Protagonist", "Leviathan Axe and Blades of Chaos",
     "Boy.",
     "The former Ghost of Sparta, now a father trying to teach his son to be better than the gods he once destroyed.", 99, 75, 70, 72),
    ("gaming", "Geralt of Rivia", "The Witcher", "The Witcher 3: Wild Hunt", "Monster Hunter", "Witcher Signs and Silver Sword",
     "Evil is evil. Lesser, greater, middling, it's all the same.",
     "A mutated monster hunter for hire whose bond with his adopted daughter Ciri defines his journey.", 86, 82, 84, 68),
    ("gaming", "Cloud Strife", "Final Fantasy VII", "Final Fantasy VII Rebirth", "Mercenary", "Buster Sword and Limit Breaks",
     "Let's mosey.",
     "A former SOLDIER turned mercenary who confronts his fractured memories while pursuing Sephiroth.", 88, 70, 85, 74),
    ("movies", "Paul Atreides", "Dune", "Dune: Part Two", "Protagonist", "Prescience and Fremen training",
     "The mystery of life isn't a problem to solve, but a reality to experience.",
     "The heir of House Atreides who becomes the Fremen messiah Muad'Dib on the desert planet Arrakis.", 70, 92, 80, 95),
    ("movies", "Miles Morales", "Spider-Verse", "Spider-Man: Across the Spider-Verse", "Hero", "Venom Blast and Camouflage",
     "Anyone can wear the mask.",
     "A Brooklyn teenager and artist who became Spider-Man and challenges the rules of the Multiverse.", 76, 80, 94, 85),
    ("movies", "Tony Stark", "Avengers", "Avengers: Endgame", "Hero", "Iron Man armor",
     "I am Iron Man.",
     "The genius inventor who built the Iron Man suit and made the ultimate sacrifice to save the universe.", 82, 99, 75, 96),
    ("movies", "The Joker", "The Dark Knight", "The Dark Knight", "Villain", "Chaos and manipulation",
     "Why so serious?",
     "An agent of chaos who tests Gotham's morality and Batman's code in The Dark Knight.", 55, 92, 60, 88),
    ("tv-shows", "Eleven", "Stranger Things", "Stranger Things", "Protagonist", "Telekinesis",
     "Friends don't lie.",
     "A girl with psychokinetic abilities who escaped Hawkins Lab and became the heart of her friend group.", 60, 70, 55, 82),
    ("tv-shows", "Joel Miller", "The Last of Us", "The Last of Us", "Protagonist", "Survival instinct",
     "You keep finding something to fight for.",
     "A hardened smuggler whose mission to escort Ellie becomes the reason he keeps living.", 80, 72, 68, 66),
    ("tv-shows", "Jinx", "Arcane", "Arcane", "Anti-hero", "Hextech inventions",
     "I'm not a monster. I'm just ahead of the curve.",
     "A brilliant, unpredictable inventor from Zaun whose broken bond with her sister Vi drives the story.", 58, 90, 88, 84),
    ("tv-shows", "Walter White", "Breaking Bad", "Breaking Bad", "Anti-hero", "Chemistry genius",
     "I am the one who knocks.",
     "A chemistry teacher who turns to manufacturing methamphetamine and becomes the infamous Heisenberg.", 40, 97, 35, 80),
    ("k-pop", "BTS", "BTS", "BTS - Map of the Soul: 7", "Group", "Global stadium performances",
     "Love yourself, love myself, peace.",
     "A seven-member group that broke global records and became one of the best-selling acts in history.", 85, 88, 92, 99),
    ("k-pop", "BLACKPINK", "BLACKPINK", "BLACKPINK - Born Pink", "Group", "Headline performances",
     "BLACKPINK in your area.",
     "A four-member girl group known for bold concepts and record-breaking music videos.", 82, 85, 90, 98),
    ("k-pop", "Stray Kids", "Stray Kids", "Stray Kids - 5-STAR", "Group", "Self-produced sound",
     "Stay, we're here for you.",
     "An eight-member group whose in-house producer unit 3RACHA writes much of their music.", 84, 86, 91, 93),
    ("k-pop", "NewJeans", "NewJeans", "NewJeans - Get Up", "Group", "Signature Y2K style",
     "Bunnies, we're always together.",
     "A five-member group recognised for its easy-listening sound and nostalgic visual identity.", 78, 84, 88, 95),
    ("comics", "Rorschach", "Watchmen", "Watchmen", "Vigilante", "Unyielding resolve",
     "Never compromise. Not even in the face of Armageddon.",
     "A masked vigilante with a shifting inkblot face and an absolute moral code.", 72, 80, 74, 40),
    ("comics", "Dream of the Endless", "The Sandman", "The Sandman", "Protagonist", "Lord of the Dreaming",
     "I am hope.",
     "The anthropomorphic personification of dreams, rebuilding his kingdom after a century in captivity.", 90, 96, 70, 86),
    ("comics", "Batman", "DC Comics", "Batman: Year One", "Hero", "Detective skills and gadgets",
     "I am vengeance. I am the night.",
     "Bruce Wayne, the Dark Knight of Gotham City, who turned tragedy into a lifelong crusade.", 85, 96, 88, 80),
    ("comics", "Mark Grayson", "Invincible", "Invincible", "Hero", "Viltrumite strength and flight",
     "I'm not going to let you hurt anyone else.",
     "The son of Omni-Man who must decide what kind of hero he will become.", 95, 70, 92, 78),
    ("manga", "Guts", "Berserk", "Berserk", "Protagonist", "Dragonslayer and Berserker Armor",
     "If you're always worried about crushing the ants beneath you, you won't be able to walk.",
     "The Black Swordsman, a mercenary who survives impossible odds on his path of vengeance.", 98, 70, 78, 60),
    ("manga", "Light Yagami", "Death Note", "Death Note", "Anti-hero", "The Death Note",
     "I am justice!",
     "A brilliant student who uses a supernatural notebook to become the god of a new world.", 40, 99, 50, 90),
    ("manga", "Thorfinn", "Vinland Saga", "Vinland Saga", "Protagonist", "Dual daggers and resolve",
     "I have no enemies.",
     "A Viking warrior who trades revenge for a vision of a land without war.", 82, 76, 92, 70),
    ("manga", "Yoichi Isagi", "Blue Lock", "Blue Lock", "Striker", "Spatial awareness",
     "I'm going to become the best striker in the world.",
     "A striker whose spatial awareness and adaptability make him a standout of the Blue Lock project.", 70, 90, 86, 74),
    ("cosplay", "Marin Kitagawa", "My Dress-Up Darling", None, "Cosplayer", "Endless enthusiasm",
     "Loving something is never something to be ashamed of.",
     "A cheerful student whose passion for cosplay inspires friends to follow their own creative dreams.", 50, 72, 70, 97),
    ("cosplay", "2B", "NieR:Automata", None, "Android", "Virtuous Contract blade",
     "Everything that lives is designed to end.",
     "An elite YoRHa combat android and one of the most-cosplayed game characters in the world.", 88, 80, 95, 84),
    ("cosplay", "Makima", "Chainsaw Man", "Chainsaw Man", "Antagonist", "Control Devil",
     "Good dogs are rewarded.",
     "The enigmatic Public Safety leader whose calm authority makes her a convention favorite.", 80, 95, 70, 96),
    ("cosplay", "Harley Quinn", "DC Comics", None, "Anti-hero", "Acrobatics and a giant mallet",
     "Life is a game, and I'm the one with the rules.",
     "A former psychiatrist turned chaotic anti-hero whose costumes are cosplay staples.", 70, 78, 92, 90),
]

# ---------------------------------------------------------------------------
# MERCHANDISE (display only): (category, name, fandom, manufacturer, tags,
#                              description, isUpcoming)
# ---------------------------------------------------------------------------
MERCH = [
    ("anime", "Survey Corps Cloak Replica", "Attack on Titan", "Studio Replica Works", ["Collectible", "Official"],
     "Full-length green cloak with the Wings of Freedom emblem embroidered on the back.", False),
    ("anime", "Nichirin Sword Display Set", "Demon Slayer", "Blade Atelier", ["Limited Edition", "Collectible"],
     "Display-grade replica blade with a lacquered stand and certificate of authenticity.", False),
    ("anime", "Satoru Gojo 1/7 Scale Figure", "Jujutsu Kaisen", "Figure Forge", ["Pre-Order", "Collectible"],
     "Highly detailed scale figure capturing Gojo's Domain Expansion pose.", True),
    ("anime", "Thousand Sunny Model Kit", "One Piece", "Grand Line Models", ["Fan Favorite", "New Arrival"],
     "Snap-fit ship model kit with lion figurehead and display base.", False),
    ("gaming", "Master Sword Replica", "The Legend of Zelda", "Hylian Forge", ["Collectible", "Limited Edition"],
     "Full-scale replica with a detailed hilt and matching wall mount.", False),
    ("gaming", "Elden Ring Collector's Statue", "Elden Ring", "Tarnished Studios", ["Limited Edition", "Exclusive"],
     "Sculpted statue of Malenia, Blade of Miquella, on a scarlet rot base.", False),
    ("gaming", "Leviathan Axe Replica", "God of War", "Nine Realms Replicas", ["Collectible", "Official"],
     "Frost-etched axe replica with runic detailing and display hook.", False),
    ("gaming", "Samurai Jacket Replica", "Cyberpunk 2077", "Night City Apparel", ["Pre-Order", "Fan Favorite"],
     "Jacket inspired by the Samurai band look, with illuminated collar trim.", True),
    ("movies", "Stillsuit Prop Replica", "Dune", "Arrakis Prop Co.", ["Limited Edition", "Collectible"],
     "Wearable costume replica inspired by the Fremen stillsuit.", False),
    ("movies", "Miles Morales Action Figure", "Spider-Verse", "Multiverse Toys", ["New Arrival", "Fan Favorite"],
     "Poseable figure with interchangeable hands and web effect parts.", False),
    ("movies", "Infinity Gauntlet Replica", "Avengers", "Cosmic Replica Co.", ["Collectible", "Exclusive"],
     "Life-size gauntlet with light-up Infinity Stones.", False),
    ("movies", "Tumbler Die-Cast Vehicle", "The Dark Knight", "Gotham Die-Cast", ["Collectible"],
     "1:18 scale die-cast Tumbler with rubber tires and detailed interior.", False),
    ("tv-shows", "Hellfire Club Tee", "Stranger Things", "Hawkins Apparel", ["Official", "Fan Favorite"],
     "Soft cotton tee featuring the Hellfire Club crest.", False),
    ("tv-shows", "Jinx Premium Figure", "Arcane", "Zaun Figures", ["Pre-Order", "Limited Edition"],
     "Premium figure of Jinx with Fishbones and interchangeable face plates.", True),
    ("tv-shows", "Beskar Helmet Replica", "The Mandalorian", "Mandalore Forge", ["Collectible", "Limited Edition"],
     "Wearable helmet replica with metallic finish and padded interior.", False),
    ("tv-shows", "Dragon Egg Display Trio", "House of the Dragon", "Targaryen Treasures", ["Collectible", "Exclusive"],
     "Set of three resin dragon eggs on a sculpted display stand.", False),
    ("k-pop", "Official Light Stick Ver. 4", "BTS", "BIGHIT MUSIC", ["Official", "Fan Favorite"],
     "Bluetooth-synced light stick for concert light shows.", False),
    ("k-pop", "Hammer Light Stick", "BLACKPINK", "YG Select", ["Official", "Collectible"],
     "The iconic heart-hammer light stick with concert sync mode.", False),
    ("k-pop", "5-STAR Album Set", "Stray Kids", "JYP Entertainment", ["Official", "New Arrival"],
     "All album versions with photobooks, photocards and posters.", False),
    ("k-pop", "Bunny Plush Keyring", "NewJeans", "ADOR", ["Limited Edition", "Pre-Order"],
     "Soft plush keyring inspired by the group's bunny mascot.", True),
    ("comics", "Watchmen Absolute Edition", "Watchmen", "DC Comics", ["Collectible", "Official"],
     "Oversized hardcover with recolored art and bonus material.", False),
    ("comics", "The Sandman Omnibus", "The Sandman", "DC Comics", ["Collectible", "Fan Favorite"],
     "Complete Sandman run collected in a premium omnibus.", False),
    ("comics", "Invincible Compendium", "Invincible", "Image Comics", ["New Arrival"],
     "A massive collection of the Invincible saga in one volume.", False),
    ("comics", "Cowl Replica", "Batman", "Gotham Prop Works", ["Limited Edition", "Exclusive"],
     "Wearable cowl replica with a matte armored finish.", True),
    ("manga", "Berserk Deluxe Edition Vol. 1", "Berserk", "Dark Horse", ["Collectible", "Official"],
     "Hardcover deluxe edition collecting the first three volumes.", False),
    ("manga", "Death Note Replica Notebook", "Death Note", "Shinigami Goods", ["Fan Favorite", "Collectible"],
     "Faux-leather notebook replica with printed rules pages.", False),
    ("manga", "Vagabond Illustration Book", "Vagabond", "Inoue Art", ["Limited Edition", "Collectible"],
     "Large-format ink and watercolor illustrations from the series.", False),
    ("manga", "Blue Lock Training Jersey", "Blue Lock", "Egoist Sportswear", ["Pre-Order", "New Arrival"],
     "Breathable training jersey with the Blue Lock logo.", True),
    ("cosplay", "Pro Worbla Sheet Kit", "Cosplay Crafting", "Maker Supply", ["New Arrival", "Official"],
     "Thermoplastic sheets, heat gun guide and primer kit.", False),
    ("cosplay", "Heat-Resistant Styling Wig Set", "Cosplay Crafting", "Wig Lab", ["Fan Favorite"],
     "Three styling wigs with lace fronts and spike-friendly fibers.", False),
    ("cosplay", "LED Prop Electronics Kit", "Cosplay Crafting", "Glow Workshop", ["Pre-Order", "Exclusive"],
     "Pre-wired LED strips, battery packs and switches for props.", True),
    ("cosplay", "Fantasy Sewing Pattern Pack", "Cosplay Crafting", "Pattern House", ["Limited Edition"],
     "Printable patterns for capes, tunics and armor underlayers.", False),
]

# ---------------------------------------------------------------------------
# UPCOMING RELEASES: (category, title, releaseType, date, isConfirmed, studio,
#                     description, tags)
# ---------------------------------------------------------------------------
UPCOMING = [
    ("gaming", "Grand Theft Auto VI", "Game", "2026-11-19", True, "Rockstar Games",
     "Rockstar's return to Vice City, following Lucia and Jason across the state of Leonida.", ["Pre-Order", "Trending"]),
    ("movies", "Avengers: Doomsday", "Movie", "2026-12-18", True, "Marvel Studios",
     "The Avengers face Victor von Doom in the next chapter of the Multiverse Saga.", ["Trending", "Official"]),
    ("movies", "Dune: Part Three", "Movie", "2026-12-18", True, "Legendary Pictures",
     "Denis Villeneuve adapts Dune Messiah, continuing Paul Atreides' story.", ["Official"]),
    ("movies", "The Batman Part II", "Movie", "2027-10-01", True, "DC Studios",
     "Matt Reeves' sequel continues Bruce Wayne's second year as Gotham's protector.", ["Official"]),
    ("movies", "Avengers: Secret Wars", "Movie", "2027-12-17", True, "Marvel Studios",
     "The finale of the Multiverse Saga.", ["Trending"]),
    ("gaming", "Marvel's Wolverine", "Game", "2026-10-15", False, "Insomniac Games",
     "An original Wolverine action game from the studio behind Marvel's Spider-Man.", ["Pre-Order"]),
    ("gaming", "The Witcher IV", "Game", "2027-06-30", False, "CD Projekt Red",
     "A new saga starring Ciri as a fully fledged witcher.", ["Trending"]),
    ("anime", "Fan Hub Plus Anime Night: Winter Season Preview", "Anime", "2026-12-12", True, "Fan Hub Plus",
     "A platform watch-party previewing the most anticipated shows of the winter season.", ["Exclusive"]),
    ("tv-shows", "Fan Hub Plus Premiere Watch-Along", "Show", "2026-11-07", True, "Fan Hub Plus",
     "A live community watch-along for a major streaming premiere with trivia and polls.", ["Exclusive"]),
    ("k-pop", "Realm Light Stick Charm Drop", "Merch Drop", "2026-10-30", True, "Fan Hub Plus Store Partners",
     "Collectible light stick charms themed to each of the eight realms.", ["Limited Edition", "Collectible"]),
    ("comics", "Multiverse Variant Cover Series", "Comic", "2026-11-25", True, "Fan Hub Plus Creators",
     "Eight community-designed variant covers, one for every realm.", ["Limited Edition", "Collectible"]),
    ("manga", "Ink Masters Artbook Vol. 2", "Comic", "2027-01-20", False, "Fan Hub Plus Creators",
     "A collection of fan-submitted manga illustrations selected by the community.", ["Pre-Order"]),
    ("cosplay", "Realm Armor Pattern Pack", "Merch Drop", "2026-10-22", True, "Fan Hub Plus Studio",
     "Printable foam armor patterns inspired by the eight realm emblems.", ["New Arrival"]),
    ("anime", "Nexus Portal 1/6 Statue", "Merch Drop", "2027-02-14", False, "Fan Hub Plus Store Partners",
     "A light-up statue of the Fan Hub Plus Nexus portal.", ["Pre-Order", "Limited Edition"]),
    ("k-pop", "Stage Lights Photocard Collection", "Merch Drop", "2026-12-01", True, "Fan Hub Plus Store Partners",
     "A holographic photocard binder set celebrating K-Pop stage design.", ["Collectible"]),
    ("tv-shows", "Season Finale Marathon Weekend", "Show", "2027-03-06", False, "Fan Hub Plus",
     "A two-day community marathon of fan-voted season finales.", ["Exclusive"]),
]

# ---------------------------------------------------------------------------
# EVENTS: (category|None, title, type, city, country, venue, lat, lng, start,
#          end, ticketUrl, isHighlight, description, story)
# Dates are sample test data; admins edit them from the Control Panel.
# ---------------------------------------------------------------------------
EVENTS = [
    ("comics", "New York Comic Con", "Convention", "New York", "USA", "Javits Center", 40.7577, -74.0027, "2026-10-08", "2026-10-11",
     "https://www.newyorkcomiccon.com", True, "The East Coast's biggest celebration of comics, film, TV, games and cosplay.",
     "Four days of panels, exclusive reveals and a show floor where every realm meets under one roof."),
    ("cosplay", "MCM London Comic Con", "Convention", "London", "UK", "ExCeL London", 51.5081, 0.0294, "2026-10-23", "2026-10-25",
     "https://www.mcmcomiccon.com", True, "The UK's leading pop culture event with a legendary cosplay masquerade.",
     "Thousands of cosplayers fill ExCeL for three days, and the masquerade stage crowns the country's top builders."),
    ("comics", "Lucca Comics & Games", "Convention", "Lucca", "Italy", "Historic Centre", 43.8429, 10.5027, "2026-10-28", "2026-11-01",
     "https://www.luccacomicsandgames.com", True, "Europe's largest comics and games festival held inside a walled medieval city.",
     "Medieval streets transform into a living fandom universe with exhibitions, tournaments and parades."),
    ("gaming", "Paris Games Week", "Convention", "Paris", "France", "Paris Expo Porte de Versailles", 48.8322, 2.2875, "2026-10-29", "2026-11-02",
     "https://www.parisgamesweek.com", False, "France's largest video game show with playable demos and esports stages.",
     "Players line up for unreleased demos while esports finals light up the main arena."),
    ("anime", "Comic Market (Comiket)", "Convention", "Tokyo", "Japan", "Tokyo Big Sight", 35.6298, 139.7942, "2026-12-29", "2026-12-30",
     "https://www.comiket.co.jp", True, "The world's largest self-published comics fair.",
     "Circle tables stretch as far as the eye can see, filled with doujinshi from creators of every fandom."),
    ("anime", "Jump Festa", "Convention", "Chiba", "Japan", "Makuhari Messe", 35.6480, 140.0346, "2026-12-19", "2026-12-20",
     "https://www.jumpfesta.com", False, "Shueisha's annual festival of Weekly Shonen Jump anime, manga and games.",
     "Stage events reveal next year's anime adaptations and game announcements for Jump's biggest series."),
    ("gaming", "PAX East", "Convention", "Boston", "USA", "Boston Convention Center", 42.3453, -71.0450, "2027-03-25", "2027-03-28",
     "https://east.paxsite.com", False, "A celebration of gaming culture with indie showcases and tabletop halls.",
     "Indie developers, tabletop tournaments and concerts make PAX a player-first festival."),
    ("anime", "Anime Expo", "Convention", "Los Angeles", "USA", "Los Angeles Convention Center", 34.0403, -118.2696, "2027-07-02", "2027-07-05",
     "https://www.anime-expo.org", True, "North America's largest celebration of Japanese pop culture.",
     "Premieres, concerts and the Masquerade bring the anime community together every July in Los Angeles."),
    ("comics", "San Diego Comic-Con", "Convention", "San Diego", "USA", "San Diego Convention Center", 32.7065, -117.1618, "2027-07-22", "2027-07-25",
     "https://www.comic-con.org", True, "The legendary convention where Hall H reveals shape the year in pop culture.",
     "Hall H lines form overnight as studios bring casts, trailers and surprises to the most famous stage in fandom."),
    ("gaming", "gamescom", "Convention", "Cologne", "Germany", "Koelnmesse", 50.9466, 6.9828, "2027-08-25", "2027-08-29",
     "https://www.gamescom.global", True, "The world's largest gaming event with Opening Night Live.",
     "Opening Night Live kicks off five days of world premieres and hands-on demos."),
    ("gaming", "Tokyo Game Show", "Convention", "Chiba", "Japan", "Makuhari Messe", 35.6480, 140.0346, "2027-09-23", "2027-09-26",
     "https://tgs.nikkeibp.co.jp", False, "Asia's premier game expo featuring major Japanese publishers.",
     "Japanese studios showcase their biggest titles and cosplayers line the halls between stages."),
    ("anime", "Japan Expo", "Convention", "Paris", "France", "Paris-Nord Villepinte", 48.9731, 2.5156, "2027-07-08", "2027-07-11",
     "https://www.japan-expo-paris.com", False, "Europe's largest festival of Japanese culture, from manga to martial arts.",
     "Manga artists, J-Pop concerts and traditional culture share the stage for four days."),
    ("k-pop", "KCON LA", "Convention", "Los Angeles", "USA", "Crypto.com Arena", 34.0430, -118.2673, "2027-08-13", "2027-08-15",
     "https://www.kconusa.com", True, "A K-Pop convention and concert series celebrating Korean culture.",
     "Fan engagement by day, stadium-scale concerts by night: KCON is the K-Pop fan's summer pilgrimage."),
    ("anime", "Otakon", "Convention", "Washington, D.C.", "USA", "Walter E. Washington Convention Center", 38.9048, -77.0230, "2027-08-06", "2027-08-08",
     "https://www.otakon.com", False, "A long-running fan-run celebration of East Asian pop culture.",
     "Run by fans for fans, Otakon blends panels, concerts and a vibrant artist alley."),
    ("cosplay", "Dragon Con", "Convention", "Atlanta", "USA", "Downtown Atlanta Hotels", 33.7590, -84.3880, "2027-09-02", "2027-09-06",
     "https://www.dragoncon.org", False, "A multi-genre convention famous for its cosplay parade.",
     "The Dragon Con parade turns downtown Atlanta into a street-level celebration of costumes."),
    ("manga", "Anime NYC", "Convention", "New York", "USA", "Javits Center", 40.7577, -74.0027, "2027-08-20", "2027-08-22",
     "https://animenyc.com", False, "New York's anime convention featuring manga publishers and premieres.",
     "Manga publishers announce new licenses while fans meet their favorite creators."),
    ("cosplay", "Fan Hub Plus Cosplay Meetup - Karachi", "Meetup", "Karachi", "Pakistan", "Port Grand", 24.8454, 66.9856, "2026-10-17", "2026-10-17",
     "https://fanhubplus.example/events/karachi-cosplay-meetup", True, "A seaside meetup for cosplayers with a photo walk and craft swap.",
     "Cosplayers gather at sunset for a photo walk along the waterfront followed by a prop-making swap table."),
    ("anime", "Fan Hub Plus Anime Screening Night - Lahore", "Screening", "Lahore", "Pakistan", "Alhamra Arts Council", 31.5580, 74.3355, "2026-11-14", "2026-11-14",
     "https://fanhubplus.example/events/lahore-screening", False, "A big-screen anime film night with a community quiz.",
     "A packed hall watches a fan-voted classic, followed by trivia and a cosplay showcase."),
    ("gaming", "Fan Hub Plus Game Night - Islamabad", "Meetup", "Islamabad", "Pakistan", "F-9 Park Pavilion", 33.7010, 73.0250, "2026-11-28", "2026-11-28",
     "https://fanhubplus.example/events/islamabad-game-night", False, "Retro and modern game stations with a fighting-game bracket.",
     "Players compete in a community bracket while newcomers try classic consoles."),
    ("k-pop", "Fan Hub Plus K-Pop Random Play Dance - Karachi", "Meetup", "Karachi", "Pakistan", "Dolmen Mall Clifton Atrium", 24.8023, 67.0303, "2026-12-05", "2026-12-05",
     "https://fanhubplus.example/events/karachi-rpd", False, "A random play dance session for K-Pop dance covers.",
     "Songs shuffle, dancers jump in, and the crowd cheers every perfectly timed chorus."),
    ("movies", "Fan Hub Plus Premiere Night - Dubai", "Premiere", "Dubai", "UAE", "Dubai Mall Cinema", 25.1972, 55.2796, "2026-12-18", "2026-12-18",
     "https://fanhubplus.example/events/dubai-premiere-night", True, "A community premiere screening with themed photo zones.",
     "Fans in costume gather for opening night, with photo zones inspired by the film's world."),
    ("manga", "Fan Hub Plus Manga Drawing Jam - Lahore", "Meetup", "Lahore", "Pakistan", "National College of Arts", 31.5686, 74.3094, "2027-01-16", "2027-01-16",
     "https://fanhubplus.example/events/lahore-drawing-jam", False, "An ink-and-paper drawing jam for aspiring manga artists.",
     "Artists sketch side by side, trade panel techniques and exhibit their pages by the evening."),
    ("tv-shows", "Fan Hub Plus Series Finale Party - London", "Screening", "London", "UK", "Prince Charles Cinema", 51.5114, -0.1302, "2027-02-06", "2027-02-06",
     "https://fanhubplus.example/events/london-finale-party", False, "A finale screening with fan theories and a live quiz.",
     "The audience trades theories before the lights dim, then celebrates together after the credits."),
    ("comics", "Fan Hub Plus Comic Swap - Toronto", "Meetup", "Toronto", "Canada", "Toronto Reference Library", 43.6719, -79.3868, "2027-03-13", "2027-03-13",
     "https://fanhubplus.example/events/toronto-comic-swap", False, "Trade back issues and meet local creators.",
     "Long boxes line the tables as collectors trade issues and discover local independent creators."),
]

# ---------------------------------------------------------------------------
# ARTICLES: (category, title, excerpt, [paragraphs], [(dateLabel, title, desc)])
# ---------------------------------------------------------------------------
ARTICLES = [
    ("anime", "How Anime Conquered the World",
     "From late-night cult favorite to global streaming phenomenon, a look at the milestones that took anime mainstream.",
     ["Anime was once a niche discovered through fan-subbed tapes and late-night broadcasts. Today it tops global streaming charts and fills stadium-sized conventions.",
      "Landmark films proved animation could carry adult emotion and spectacle, while long-running series built communities that grew with their audiences year after year.",
      "Streaming removed the final barrier. Simulcasts let fans on every continent watch new episodes within hours of Japan, turning each weekly release into a worldwide event."],
     [("1998", "Cowboy Bebop airs", "A jazz-soaked space western becomes a gateway series for international audiences."),
      ("2003", "Spirited Away wins the Oscar", "Studio Ghibli's film wins the Academy Award for Best Animated Feature."),
      ("2013", "Attack on Titan premieres", "The series becomes a global phenomenon across its four seasons."),
      ("2020", "Mugen Train breaks records", "Demon Slayer: Mugen Train becomes Japan's highest-grossing film."),
      ("2023", "Frieren begins", "A reflective fantasy series quickly rises to the top of fan rankings.")]),
    ("gaming", "Open Worlds: A Decade of Player Freedom",
     "The open-world games that redefined exploration, from Skyrim's mountains to the Lands Between.",
     ["Open-world design promises one thing: if you can see it, you can go there. Over the last decade that promise evolved into living ecosystems and emergent stories.",
      "Developers learned to guide players without walls, using landmarks, light and curiosity rather than waypoints.",
      "The result is a genre where every player's journey is different, and communities trade discoveries like treasure maps."],
     [("2011", "The Elder Scrolls V: Skyrim", "A mountain-filled province becomes the template for freedom."),
      ("2015", "The Witcher 3: Wild Hunt", "Side quests with main-story depth raise the bar for writing."),
      ("2017", "Breath of the Wild", "Systemic physics and chemistry turn Hyrule into a playground."),
      ("2018", "Red Dead Redemption 2", "A meticulously detailed frontier world sets a new standard."),
      ("2022", "Elden Ring", "FromSoftware brings soulslike challenge to an open world."),
      ("2023", "Tears of the Kingdom", "Ultrahand building expands open-world creativity.")]),
    ("movies", "The Spider-Verse Effect",
     "How two animated films rewrote the rules of what a superhero movie can look like.",
     ["Into the Spider-Verse arrived with a comic-book visual language: halftone dots, frame-rate shifts and hand-drawn effects layered over CG.",
      "Its success sparked a wave of stylized animation across the industry, with studios embracing painterly and graphic looks.",
      "Across the Spider-Verse pushed further, giving every universe its own art style and proving audiences crave visual invention."],
     [("2018", "Into the Spider-Verse releases", "Miles Morales takes the lead in a visually groundbreaking film."),
      ("2019", "Academy Award win", "The film wins Best Animated Feature."),
      ("2023", "Across the Spider-Verse", "The sequel expands the Multiverse with dozens of art styles.")]),
    ("tv-shows", "Prestige TV and the Age of Adaptation",
     "Why games, novels and animation are now the richest source of award-winning television.",
     ["Television budgets now rival feature films, and adaptations have become the most reliable path to event-level series.",
      "Game adaptations, once dismissed, now earn critical acclaim by focusing on character over spectacle.",
      "For fans, it means beloved worlds get the time and craft they deserve across full seasons."],
     [("2011", "Game of Thrones premieres", "Fantasy becomes prestige television."),
      ("2021", "Arcane debuts", "An animated game adaptation earns wide critical praise."),
      ("2023", "The Last of Us airs", "A game adaptation becomes a critical and audience hit."),
      ("2024", "Shogun's Emmy record", "Shogun wins a record number of Emmys for a single season.")]),
    ("k-pop", "K-Pop's Global Stage",
     "The performances and milestones that turned K-Pop into a worldwide movement.",
     ["K-Pop combines tightly choreographed performance, visual storytelling and direct fan engagement.",
      "Fandoms organize streaming, charity projects and light-stick oceans that make every concert a shared spectacle.",
      "Each milestone opened doors for the next generation of groups to reach audiences around the world."],
     [("2012", "Gangnam Style", "PSY's video becomes the first on YouTube to pass one billion views."),
      ("2017", "BTS at the AMAs", "BTS perform on a major US awards stage."),
      ("2019", "BLACKPINK at Coachella", "The group performs at the festival."),
      ("2020", "Dynamite tops the Hot 100", "BTS earn their first Billboard Hot 100 number one."),
      ("2023", "BLACKPINK headline Coachella", "The first Asian act to headline the festival.")]),
    ("comics", "Watchmen at 40: Why It Still Matters",
     "Alan Moore and Dave Gibbons' landmark series continues to shape how we think about heroes.",
     ["Watchmen asked what costumed heroes would really mean in a world on the brink of nuclear war.",
      "Its nine-panel grid, mirrored structure and layered storytelling made it a textbook of the comics form.",
      "Four decades later, its questions about power and accountability echo across film, television and games."],
     [("1986", "Issue #1 is published", "The twelve-issue limited series begins."),
      ("1988", "Hugo Award", "Watchmen receives a Hugo Award."),
      ("2009", "Feature film", "Zack Snyder's adaptation reaches cinemas."),
      ("2019", "HBO series", "A continuation series premieres on television.")]),
    ("manga", "Dark Fantasy's Golden Age",
     "How Berserk inspired a generation of creators from manga to soulslike games.",
     ["Kentaro Miura's Berserk combined operatic scale with intimate tragedy, and its influence is visible across modern dark fantasy.",
      "Game designers have openly cited its armor, beasts and bleak beauty as inspiration.",
      "Its continuation after Miura's passing shows how a creative legacy can be carried forward with care."],
     [("1989", "Berserk begins serialization", "Guts's journey begins in Young Animal."),
      ("2009", "Demon's Souls", "A new genre of challenging dark fantasy games emerges."),
      ("2021", "Kentaro Miura passes away", "The creator's death is mourned worldwide."),
      ("2022", "Berserk continues", "Studio Gaga and Kouji Mori continue the story."),
      ("2022", "Elden Ring releases", "Dark fantasy reaches a massive global audience.")]),
    ("cosplay", "Cosplay 101: From First Costume to Masquerade Stage",
     "A step-by-step roadmap for your first serious build, from reference sheets to stage walk-on.",
     ["Every great cosplay begins with references: front, back and side views of the character plus close-ups of materials.",
      "Break the build into sections - fabric, armor, wig, props and makeup - and schedule each against your convention date.",
      "Finally, rehearse. Judges reward confident character performance as much as craftsmanship."],
     [("Week 1", "Research and references", "Collect reference images and decide on materials."),
      ("Week 2-3", "Patterning", "Draft patterns for fabric and foam pieces."),
      ("Week 4-6", "Construction", "Sew, cut, heat-shape and assemble major parts."),
      ("Week 7", "Paint and details", "Prime, paint and weather props and armor."),
      ("Week 8", "Rehearsal", "Practice poses and a short stage routine.")]),
    ("gaming", "Behind the Soundtrack: When Game Music Became Concert Music",
     "Orchestras around the world now sell out performances of video game scores.",
     ["Game music was once limited by tiny sound chips, yet composers created melodies that generations still hum.",
      "As hardware evolved, scores grew into full orchestral works recorded with live ensembles.",
      "Today symphony orchestras tour game music concerts, introducing classical halls to new audiences."],
     [("Chiptune era", "Melody under limits", "Composers write memorable themes with only a few channels."),
      ("CD era", "Recorded music", "Games begin to include fully recorded tracks."),
      ("Orchestral era", "Live ensembles", "Blockbuster games record with full orchestras."),
      ("Concert era", "Symphony tours", "Game scores fill concert halls worldwide.")]),
    ("movies", "Convention Season Guide 2026-27",
     "Plan your year: the biggest conventions and Fan Hub Plus meetups on the calendar.",
     ["Convention season never really ends. From autumn comic cons to summer anime expos, there is always a stage to visit.",
      "Use the Fan Hub Plus Event Map to find events near you, bookmark them and follow ticket links.",
      "Here is a quick timeline of the highlights on this year's calendar."],
     [("Oct 2026", "New York Comic Con", "The season opens in New York."),
      ("Oct 2026", "MCM London", "Cosplay masquerade and panels."),
      ("Dec 2026", "Comiket", "The winter edition in Tokyo."),
      ("Jul 2027", "Anime Expo", "The summer gathering in Los Angeles."),
      ("Jul 2027", "San Diego Comic-Con", "Hall H reveals return.")]),
    ("tv-shows", "Building a Fandom Community",
     "What makes an online fan community welcoming, safe and fun to come back to.",
     ["Healthy communities start with clear guidelines and moderators who enforce them fairly.",
      "Shared rituals - watch-alongs, weekly threads and events - give members a reason to return.",
      "Most importantly, communities thrive when members can create, not just consume. That is why Fan Hub Plus supports fan submissions."],
     [("Step 1", "Set guidelines", "Publish clear rules and a code of conduct."),
      ("Step 2", "Create rituals", "Host recurring watch-alongs and discussion threads."),
      ("Step 3", "Celebrate creators", "Feature fan art, articles and cosplay."),
      ("Step 4", "Meet offline", "Organize meetups and convention gatherings.")]),
    ("anime", "Studio Spotlight: The Art of the Opening Sequence",
     "Why anime openings are some of the most rewatched minutes in animation.",
     ["An anime opening has ninety seconds to introduce characters, tone and themes while matching a song beat for beat.",
      "Studios often assign their most ambitious animators to openings, making them showcases of style.",
      "Fans rewatch, rank and debate openings, and many become as famous as the shows themselves."],
     [("0:00", "Cold open", "A striking image sets the tone."),
      ("0:20", "Character roll call", "Each hero gets a signature pose."),
      ("0:55", "The drop", "Animation matches the song's peak."),
      ("1:25", "Final key visual", "The title card lands on the last note.")]),
]

# ---------------------------------------------------------------------------
# MEDIA: (category, title, mediaType, embedType, url, duration(s), description, tags)
# local files are generated by tools/gen_media.py into backend/wwwroot/media
# ---------------------------------------------------------------------------
MEDIA = [
    ("anime", "Anime Realm Teaser", "Trailer", "file", "/media/video/anime-teaser.mp4", 30, "A cinematic tour of the Anime realm's featured series.", ["Official", "Trending"]),
    ("gaming", "Gaming Realm Teaser", "Trailer", "file", "/media/video/gaming-teaser.mp4", 30, "Highlights from the Gaming realm's most-played worlds.", ["Official"]),
    ("movies", "Movies Realm Teaser", "Trailer", "file", "/media/video/movies-teaser.mp4", 30, "A spotlight reel of landmark films in the Movies realm.", ["Official"]),
    ("tv-shows", "TV Shows Realm Teaser", "Trailer", "file", "/media/video/tv-shows-teaser.mp4", 30, "Binge-worthy series from the TV Shows realm.", ["Official"]),
    ("k-pop", "K-Pop Realm Teaser", "Trailer", "file", "/media/video/k-pop-teaser.mp4", 30, "Stage lights, albums and comebacks in the K-Pop realm.", ["Official", "Fan Favorite"]),
    ("comics", "Comics Realm Teaser", "Trailer", "file", "/media/video/comics-teaser.mp4", 30, "Panels that built modern myth.", ["Official"]),
    ("manga", "Manga Realm Teaser", "Trailer", "file", "/media/video/manga-teaser.mp4", 30, "Ink, paper and legendary arcs.", ["Official"]),
    ("cosplay", "Cosplay Realm Teaser", "Trailer", "file", "/media/video/cosplay-teaser.mp4", 30, "Craft the character, own the stage.", ["Official"]),
    ("movies", "Sintel - Open Movie", "Video", "youtube", "https://www.youtube.com/embed/eRsGyueVLvQ", 888, "Blender Foundation's fantasy short about a girl searching for her dragon (CC BY 3.0).", ["Open Movie", "Fan Favorite"]),
    ("movies", "Big Buck Bunny - Open Movie", "Video", "youtube", "https://www.youtube.com/embed/aqz-KE-bpKQ", 635, "Blender Foundation's comedy short (CC BY 3.0).", ["Open Movie"]),
    ("tv-shows", "Tears of Steel - Open Movie", "Video", "youtube", "https://www.youtube.com/embed/R6MlUcmOul8", 734, "Blender Foundation's sci-fi short (CC BY 3.0).", ["Open Movie"]),
    ("cosplay", "Explainer: Bookmarks and Notes", "Explainer", "file", "/media/video/explainer-bookmarks.mp4", 24, "How to bookmark any item and attach personal notes.", ["Tutorial"]),
    ("cosplay", "Explainer: Submitting Fan Content", "Explainer", "file", "/media/video/explainer-submissions.mp4", 24, "How fan submissions are reviewed and published.", ["Tutorial"]),
    ("gaming", "Explainer: Finding Events Near You", "Explainer", "file", "/media/video/explainer-events.mp4", 24, "Use the Event Map and GPS to find meetups nearby.", ["Tutorial"]),
    ("anime", "Sakura Blade - Original Soundtrack", "Soundtrack", "file", "/media/audio/sakura-blade.mp3", 60, "An original ambient piece composed for the Anime realm.", ["Soundtrack"]),
    ("gaming", "Pixel Quest - Original Soundtrack", "Soundtrack", "file", "/media/audio/pixel-quest.mp3", 60, "An arpeggiated chiptune-inspired theme for the Gaming realm.", ["Soundtrack"]),
    ("movies", "Spotlight Overture - Original Soundtrack", "Soundtrack", "file", "/media/audio/spotlight-overture.mp3", 60, "A cinematic swell for the Movies realm.", ["Soundtrack"]),
    ("tv-shows", "Signal Lost - Original Soundtrack", "Soundtrack", "file", "/media/audio/signal-lost.mp3", 60, "A synth pulse for the TV Shows realm.", ["Soundtrack"]),
    ("k-pop", "Neon Stage - Original Soundtrack", "Soundtrack", "file", "/media/audio/neon-stage.mp3", 60, "An upbeat dance loop for the K-Pop realm.", ["Soundtrack", "Fan Favorite"]),
    ("comics", "Halftone Hero - Original Soundtrack", "Soundtrack", "file", "/media/audio/halftone-hero.mp3", 60, "A heroic brass-style theme for the Comics realm.", ["Soundtrack"]),
    ("manga", "Ink and Silence - Original Soundtrack", "Soundtrack", "file", "/media/audio/ink-and-silence.mp3", 60, "A minimal piano-like piece for the Manga realm.", ["Soundtrack"]),
    ("cosplay", "Masquerade - Original Soundtrack", "Soundtrack", "file", "/media/audio/masquerade.mp3", 60, "A regal waltz-inspired loop for the Cosplay realm.", ["Soundtrack"]),
    ("anime", "Nexus Theme - Main Title", "Soundtrack", "file", "/media/audio/nexus-theme.mp3", 60, "The Fan Hub Plus main title theme.", ["Soundtrack", "Official"]),
    ("k-pop", "Realm Radio Episode 1", "Podcast", "file", "/media/audio/realm-radio-1.mp3", 60, "Ambient intermission from the Realm Radio series.", ["Behind the Scenes"]),
]

# ---------------------------------------------------------------------------
# FAQs for the chatbot knowledge base: (category, question, answer, keywords)
# ---------------------------------------------------------------------------
FAQS = [
    ("Platform", "What is Fan Hub Plus?", "Fan Hub Plus is a fandom universe platform that brings Anime, Gaming, Movies, TV Shows, K-Pop, Comics, Manga and Cosplay together in one place with curated content, media, events and a personal dashboard.", "what,is,fan hub,about,platform"),
    ("Platform", "Which categories are available?", "There are eight realms: Anime, Gaming, Movies, TV Shows, K-Pop, Comics, Manga and Cosplay. Open the Realms menu in the navigation bar to explore them.", "categories,realms,sections,available"),
    ("Account", "How do I create an account?", "Click Join Free in the top navigation, fill in your name, email and password, then verify your email using the link we send you.", "create,account,register,sign up,join"),
    ("Account", "I forgot my password. What should I do?", "Use Forgot Password on the login page. We will email a secure reset link that is valid for 30 minutes.", "forgot,password,reset,recover"),
    ("Account", "How do I verify my email?", "Open the verification email and click the link. You can resend it from your dashboard if it expired.", "verify,email,verification,confirm"),
    ("Account", "Can I change my avatar?", "Yes. Go to Profile and Settings and upload a JPG, PNG or WEBP image up to 2 MB.", "avatar,profile picture,photo,upload"),
    ("Account", "How do I change my favorite fandoms?", "Open Profile and Settings, add or remove favorite fandoms and choose your categories of interest, then save.", "favorite,fandoms,interests,preferences"),
    ("Features", "What is the difference between a visitor and a member?", "Visitors can browse categories, previews and basic search. Members unlock full details, media playback, advanced filters, bookmarks, ratings, notes, feedback and fan submissions.", "visitor,member,difference,limited,unlock"),
    ("Features", "How do I bookmark something?", "Click the bookmark icon on any content, character, media, article, event or merchandise card. You can add a personal note from your Bookmarks page.", "bookmark,save,favorite,later"),
    ("Features", "Can I add notes to bookmarks?", "Yes. Every bookmark can hold a personal note. Edit it from the bookmark button or the Bookmarks and Notes page.", "notes,note,bookmark"),
    ("Features", "How do I share content?", "Use the Share button to copy the link or share to WhatsApp, X or Facebook.", "share,link,whatsapp,facebook,twitter,x"),
    ("Features", "How do ratings work?", "Members can give media and content a 1-5 star rating and a thumbs up or down. Averages update instantly.", "rating,rate,stars,thumbs,like,dislike"),
    ("Features", "How do I use advanced filters?", "In the Explorer, filter by category, genre, release year, popularity and content type, then sort by latest, most popular or A-Z.", "filter,filters,search,sort,advanced"),
    ("Features", "Can I submit my own fan content?", "Yes. Members can submit articles, fan art, cosplay and theories from Submit Fan Content. An admin reviews each submission before it goes public.", "submit,fan content,article,post,publish"),
    ("Features", "How long does submission review take?", "Admins usually review submissions within 48 hours. Track the status on My Submissions: pending, approved or rejected.", "review,approval,pending,status,submission"),
    ("Features", "Where is my dashboard?", "After logging in, click your avatar and choose Dashboard to see your activity, favorites, bookmarks and recommendations.", "dashboard,home,my page"),
    ("Features", "Does Fan Hub Plus sell merchandise?", "No. The Merchandise Showcase is for discovery only. There is no cart or payment on Fan Hub Plus.", "buy,purchase,cart,payment,shop,price,merchandise"),
    ("Features", "What are Upcoming Releases?", "A calendar of anticipated anime, games, movies, shows, comics and merchandise drops with countdown timers.", "upcoming,releases,countdown,coming soon"),
    ("Events", "How do I find events near me?", "Open Events, allow location access and click Near Me. The map shows conventions, meetups and screenings around you.", "events,near me,location,gps,map,nearby"),
    ("Events", "Can I filter events by city?", "Yes. The event calendar can be filtered by city and type, and each event has a ticket link.", "city,filter,calendar,events"),
    ("Events", "Where do I buy event tickets?", "Each event includes an official ticket link that opens the organizer's website.", "ticket,tickets,book,event"),
    ("Media", "What media is available?", "The Multimedia Center has trailers, videos, animated explainers, soundtracks and podcasts, each filterable by tag and category.", "media,video,audio,trailer,podcast,soundtrack"),
    ("Media", "Why can't I play a video?", "Media playback is available to members. Log in or create a free account to unlock it.", "play,video,locked,cannot,playback"),
    ("Accessibility", "How do I switch to light mode?", "Use the sun and moon toggle in the navigation bar. Your choice is remembered.", "light mode,dark mode,theme,toggle"),
    ("Accessibility", "Can I make the text bigger?", "Yes. Use the A- / A / A+ controls in the navigation bar or in Profile and Settings.", "font,size,text,bigger,accessibility"),
    ("Accessibility", "Does the site support reduced motion?", "Yes. If your system has reduced motion enabled, 3D camera movement and heavy animations are replaced with static scenes.", "motion,animation,reduced,accessibility"),
    ("Platform", "Is there a sitemap?", "Yes. The Sitemap is at the bottom of the Home page and linked in the footer.", "sitemap,pages,navigation"),
    ("Platform", "How do I report a bug?", "Open Feedback, choose Bug, describe the issue and submit. Admins track every report.", "bug,report,issue,problem,feedback"),
    ("Platform", "How do I suggest a feature?", "Open Feedback and choose Suggestion. We read every idea.", "suggestion,feature,idea,feedback"),
    ("Platform", "Who manages the content?", "Content is curated by the Fan Hub Plus admin team, who add, edit and moderate everything through the Control Panel.", "admin,manage,content,curate"),
    ("Platform", "Is my data safe?", "Passwords are hashed, sessions use signed tokens and personal pages require authentication.", "safe,security,privacy,data,password"),
    ("Chatbot", "What can the assistant do?", "I can answer questions about Fan Hub Plus, recommend content based on your interests and guide you through the main features step by step.", "assistant,chatbot,help,what can you do"),
    ("Chatbot", "Is my chat history saved?", "For members, chat history is saved so conversations can continue later. You can view or clear it from Chat History.", "history,chat,saved,conversation"),
]

USERS = [
    # fullName, email, password, role, bio, fandoms, interestCategories
    ("Fan Hub Admin", "admin@fanhubplus.com", "Admin@123", "Admin", "Keeper of the Nexus and curator of all eight realms.", ["Attack on Titan", "Elden Ring"], ["anime", "gaming"]),
    ("Ayesha Khan", "ayesha@fanhubplus.com", "User@123", "User", "Anime binge-watcher and weekend cosplayer.", ["Demon Slayer", "Frieren", "Arcane"], ["anime", "cosplay", "tv-shows"]),
    ("Bilal Ahmed", "bilal@fanhubplus.com", "User@123", "User", "Soulslike veteran who still hums the Hollow Knight soundtrack.", ["Elden Ring", "The Witcher", "Berserk"], ["gaming", "manga"]),
    ("Sara Malik", "sara@fanhubplus.com", "User@123", "User", "K-Pop stan and comic collector.", ["BTS", "Stray Kids", "Watchmen"], ["k-pop", "comics"]),
    ("Omar Siddiqui", "omar@fanhubplus.com", "User@123", "User", "Film buff with a soft spot for Spider-Verse.", ["Spider-Verse", "Dune"], ["movies", "tv-shows"]),
]
